/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class TracingClient {
  constructor(
    endpoint: string,
    apiKey: string,
    queueCapacity: number,
    batchSize: number,
    batchTimeoutMillis: number,
    workerThreads: number
  );
  createRun(run: any): void;
}
