name: "JS Integration Tests"
description: "Run JS integration tests"
inputs:
  node-version:
    description: "Node version"
    required: true
  langchain-api-key-beta:
    description: "Langchain"
    required: true
  openai-api-key:
    description: "OpenAI API key"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"
        cache-dependency-path: "yarn.lock"

    - name: Install Yarn dependencies
      run: yarn install
      shell: bash
      working-directory: js

    - name: Run JS integration tests
      run: yarn test:integration
      shell: bash
      working-directory: js
      env:
        LANGCHAIN_TRACING_V2: "true"
        LANGCHAIN_ENDPOINT: https://beta.api.smith.langchain.com
        LANGCHAIN_API_KEY: ${{ inputs.langchain-api-key-beta }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}