name: "\U0001F41B Bug Report"
description: "Submit a bug report to help us improve LangSmith. To report a _security_ issue, please instead use the security option below."
labels: ["01 Bug Report"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a bug report. Before creating a new
        issue, please make sure to take a few moments to check the issue tracker
        for existing issues about the bug.

  - type: checkboxes
    id: tracing-method
    attributes:
      label: Tracing Method
      description: "Select whether you are tracing using LangChain or some other method:"
      options:
        - label: "SDK/Client"
        - label: "REST API"
        - label: "With LangChain"
        - label: "Other"

  - type: checkboxes
    id: runtime-language
    attributes:
      label: Language
      description: ""
      options:
        - label: "Python"
        - label: "JavaScript/TypeScript"
        - label: "Other"

  - type: checkboxes
    id: platform-environment
    attributes:
      label: Host
      description: "Indicate whether you are connected to the hosted LangSmith platform or running locally."
      options:
        - label: "Hosted (https://api.smith.langchain.com)"
        - label: "Self-hosted"
        - label: "Other"

  - type: textarea
    id: system-info
    attributes:
      label: Other System Info
      description: Please share any other system info with us. You can view this by running `langsmith env` in your terminal.
      placeholder: LangSmith SDK version, client runtime information,
    validations:
      required: true

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide a [code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem you ran into. It can be a Colab link or just a code snippet.
        If you have code snippets, error messages, stack traces please provide them here as well.
        Important! Use code tags to correctly format your code. See https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting
        Avoid screenshots when possible, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.

      placeholder: |
        Steps to reproduce the behavior:

          1.
          2.
          3.

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you would expect to happen."
