blank_issues_enabled: true
version: 2.1
contact_links:
  - name: Email
    url: https://discord.gg/6adMQxSpJS
    about: LangChain team support email
  - name: Discord
    url: https://discord.gg/langchain
    about: General community discussions
