blank_issues_enabled: true
version: 2.1
contact_links:
  - name: Support Portal
    url: https://support.langchain.com
    about: Contact technical support for enterprise support requests.
  - name: Discord
    url: https://discord.gg/6adMQxSpJS
    about: General community discussions