name: "JS Vitest Eval Runner"
description: "Run JS Vitest Eval Runner"
inputs:
  node-version:
    description: "Node version"
    required: true
  langchain-api-key-beta:
    description: "Langchain"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"
        cache-dependency-path: "js/yarn.lock"

    - name: Install Yarn dependencies
      run: yarn install
      shell: bash
      working-directory: js

    - name: Run Vitest Eval Runner
      run: yarn test:eval:vitest
      shell: bash
      working-directory: js
      env:
        LANGSMITH_TRACING_V2: "true"
        LANGSMITH_ENDPOINT: https://beta.api.smith.langchain.com
        LANGSMITH_API_KEY: ${{ inputs.langchain-api-key-beta }}
