version: '3'
services:
  # TODO: Move to the regular docker-compose.yaml once deployed
  langchain-hub:
    image: langchain/${_LANGSMITH_IMAGE_PREFIX-}langchainhub-backend:latest
    environment:
      - PORT=1985
      - LANGCHAIN_ENV=local_docker
      - LOG_LEVEL=warning
    ports:
      - 1985:1985
    depends_on:
      - langchain-db
  langchain-db:
    volumes:
        - dev-langchain-db-data:/var/lib/postgresql/data
volumes:
    dev-langchain-db-data:
