name: lint

on:
  push:
    branches: [master]
  pull_request:

env:
  POETRY_VERSION: "1.4.2"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install poetry
        run: pipx install poetry==$POETRY_VERSION
      - name: Install dependencies
        run: poetry install
        working-directory: python
      - name: Analysing the code with our lint
        run: make lint
        working-directory: python
