name: "Python Integration Tests"
description: "Run integration tests"
inputs:
  python-version:
    description: "Python version"
    required: true
  langchain-api-key-beta:
    description: "LangSmith Beta Key"
    required: true
  langchain-api-key-prod:
    description: "LangSmith Key"
    required: true
  openai-api-key:
    description: "OpenAI API key"
    required: false
  anthropic-api-key:
    description: "Anthropic API key"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Install poetry
      run: pipx install poetry==1.4.2
      shell: bash
      working-directory: python

    - name: Install dependencies
      run: |
        poetry install --with dev
        poetry run pip install -U langchain langchain_anthropic tiktoken rapidfuzz vcrpy numpy
      shell: bash
      working-directory: python

    - name: Run integration tests
      env:
        LANGSMITH_TRACING_V2: "true"
        LANGSMITH_ENDPOINT: https://beta.api.smith.langchain.com
        LANGSMITH_API_KEY: ${{ inputs.langchain-api-key-beta }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        LANGSMITH_TEST_CACHE: tests/cassettes
      run: make integration_tests_fast
      shell: bash
      working-directory: python

    - name: Run doctest
      env:
        LANGSMITH_TRACING_V2: "true"
        LANGSMITH_ENDPOINT: https://api.smith.langchain.com
        LANGSMITH_API_KEY: ${{ inputs.langchain-api-key-prod }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        LANGSMITH_TEST_CACHE: tests/cassettes
      run: make doctest
      shell: bash
      working-directory: python

    - name: Run Evaluation
      env:
          LANGSMITH_TRACING: "true"
          LANGSMITH_ENDPOINT: https://beta.api.smith.langchain.com
          LANGSMITH_API_KEY: ${{ inputs.langchain-api-key-beta }}
          OPENAI_API_KEY: ${{ inputs.openai-api-key }}
          ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
          LANGSMITH_TEST_CACHE: tests/cassettes
      run: make evals
      shell: bash
      working-directory: python
