name: "Python Integration Tests"
description: "Run integration tests"
inputs:
  python-version:
    description: "Python version"
    required: true
  langchain-api-key:
    description: "Langchain"
    required: true
  langchain-endpoint:
    description: "LangSmith Endpoint"
    required: true
  openai-api-key:
    description: "OpenAI API key"
    required: false
  anthropic-api-key:
    description: "Anthropic API key"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Install poetry
      run: pipx install poetry==1.4.2
      shell: bash
      working-directory: python

    - name: Install dependencies
      run: |
        poetry install --with dev
        poetry run pip install -U langchain langchain_anthropic tiktoken rapidfuzz vcrpy numpy
      shell: bash
      working-directory: python

    - name: Run integration tests
      env:
        LANGCHAIN_TRACING_V2: "true"
        LANGCHAIN_ENDPOINT: ${{ inputs.langchain-endpoint }}
        LANGCHAIN_API_KEY: ${{ inputs.langchain-api-key }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
      run: make integration_tests_fast
      shell: bash
      working-directory: python
    
    - name: Run doctest
      env:
        LANGCHAIN_TRACING_V2: "true"
        LANGCHAIN_ENDPOINT: ${{ inputs.langchain-endpoint }}
        LANGCHAIN_API_KEY: ${{ inputs.langchain-api-key }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
      run: make doctest
      shell: bash
      working-directory: python
    

    - name: Run Evaluation
      env:
          LANGCHAIN_TRACING_V2: "true"
          LANGCHAIN_ENDPOINT: ${{ inputs.langchain-endpoint }}
          LANGCHAIN_API_KEY: ${{ inputs.langchain-api-key }}
          OPENAI_API_KEY: ${{ inputs.openai-api-key }}
          ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
      run: make evals
      shell: bash
      working-directory: python

