name: "Integration Tests"
description: "Run integration tests"
inputs:
  python-version:
    description: "Python version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Install poetry
      run: pipx install poetry==$POETRY_VERSION
      shell: bash
      working-directory: python

    - name: Install dependencies
      run: poetry install --with dev
      shell: bash
      working-directory: python

    - name: Run integration tests
      env:
        LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
        LANGCHAIN_TRACING_V2: "true"
      run: make integration_tests
      shell: bash
      working-directory: python
