name: "Python Integration Tests"
description: "Run integration tests"
inputs:
  python-version:
    description: "Python version"
    required: true
  langchain-api-key-beta:
    description: "LangSmith Beta Key"
    required: true
  langchain-api-key-prod:
    description: "LangSmith Key"
    required: true
  openai-api-key:
    description: "OpenAI API key"
    required: false
  anthropic-api-key:
    description: "Anthropic API key"
    required: false
  gemini-api-key:
    description: "Gemini API key"
    required: false
  test-type:
    description: "Type of test to run (integration, doctest, evals, or all)"
    required: false
    default: "all"
  shard-total:
    description: "Total pytest shards (integration only)"
    required: false
    default: ""
  shard-index:
    description: "Current pytest shard index (integration only, 0-based)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}
        working-directory: python
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --group dev
        uv pip install langchain langchain-openai langchain-anthropic tiktoken rapidfuzz vcrpy numpy
      shell: bash
      working-directory: python

    - name: Run integration tests
      if: inputs.test-type == 'integration' || inputs.test-type == 'all'
      env:
        LANGSMITH_TRACING_V2: "true"
        LANGSMITH_ENDPOINT: https://beta.api.smith.langchain.com
        LANGSMITH_API_KEY: ${{ inputs.langchain-api-key-beta }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
        GOOGLE_API_KEY: ${{ inputs.gemini-api-key }}
        LANGSMITH_TEST_CACHE: tests/cassettes
        PYTEST_SHARD_TOTAL: ${{ inputs.shard-total }}
        PYTEST_SHARD_INDEX: ${{ inputs.shard-index }}
      run: make integration_tests_fast
      shell: bash
      working-directory: python

    - name: Run Evaluation
      if: inputs.test-type == 'evals' || inputs.test-type == 'all'
      env:
          LANGSMITH_TRACING: "true"
          LANGSMITH_ENDPOINT: https://beta.api.smith.langchain.com
          LANGSMITH_API_KEY: ${{ inputs.langchain-api-key-beta }}
          OPENAI_API_KEY: ${{ inputs.openai-api-key }}
          ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
          GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
          GOOGLE_API_KEY: ${{ inputs.gemini-api-key }}
          LANGSMITH_TEST_CACHE: tests/cassettes
      run: make evals
      shell: bash
      working-directory: python
