name: CodSpeed

on:
  # Runs on main record the baseline that PR runs are compared against.
  push:
    branches: [main]
    paths:
      - "python/langsmith/**"
      - "python/bench/**"
  pull_request:
    paths:
      - "python/langsmith/**"
      - "python/bench/**"
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: "Python Benchmarks"
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout
      id-token: write # required for OIDC authentication with CodSpeed
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: 3.11
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group dev --group bench

      - name: Run benchmarks
        uses: CodSpeedHQ/action@4296e51e7041e24dadb86d1d6e8b9320d223dbe8 # v5.0.3
        with:
          mode: simulation,memory
          working-directory: python
          run: uv run pytest bench/test_bench.py --codspeed
