name: "CI: Test Docker Compose"

on:
  push:
    branches: [ main ]
    paths:
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/test_docker_compose.yml"
      - "python/langsmith/cli/docker-compose.yaml"


jobs:

  docker-compose:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    env:
      LANGSMITH_LICENSE_KEY: ${{ secrets.LANGSMITH_LICENSE_KEY }}
      API_KEY_SALT: test

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: KengoTODA/actions-setup-docker-compose@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Start containers
      working-directory: python/langsmith/cli
      run: docker compose up -d

    - name: Check frontend health
      run: curl localhost:1980/ok

    - name: Check backend health
      run: curl localhost:1980/api/info

